CREATE OR REPLACE PROCEDURE ACTUALIZA_STOCK(
  FECHAINICIAL IN DATE,
  FECHAFINAL IN DATE
)
AS
  vFechaInicial date;
  vFechaFinal date;
  V_HSTOCKPK number;

  CURSOR C_TIEMPO IS
  SELECT ID_STOCK FROM H_STOCK H, D_TIEMPO T WHERE H.ID_TIEMPO = T.ID_TIEMPO AND T.FECHA BETWEEN FECHAINICIAL AND FECHAFINAL;

  CURSOR C_STOCK IS
  SELECT LIBRO, TIEMPO, CANTIDAD FROM STOCK WHERE FECHA BETWEEN FECHAINICIAL AND FECHAFINAL;

  V_HSTOCKREG C_STOCK%ROWTYPE;

BEGIN
  vFechaInicial := FECHAINICIAL;
  vFechaFinal := FECHAFINAL;

  OPEN C_TIEMPO;
  FETCH C_TIEMPO INTO V_HSTOCKPK;

  WHILE C_TIEMPO%FOUND LOOP
    DELETE FROM H_STOCK WHERE ID_STOCK = V_HSTOCKPK;
    FETCH C_TIEMPO INTO V_HSTOCKPK;
  END LOOP;
  CLOSE C_TIEMPO;

  OPEN C_STOCK;

  FETCH C_STOCK INTO V_HSTOCKREG;
  WHILE C_STOCK%FOUND LOOP
    INSERT INTO H_STOCK VALUES(SEQ_H_STOCK.NEXTVAL, V_HSTOCKREG.LIBRO, V_HSTOCKREG.TIEMPO, V_HSTOCKREG.CANTIDAD);
    FETCH C_STOCK INTO V_HSTOCKREG;
  END LOOP;
CLOSE C_STOCK;
COMMIT;
END ACTUALIZA_STOCK;
EXECUTE ACTUALIZA_STOCK(to_date('01-01-2017'), to_date('31-12-2017'));
