CREATE OR REPLACE VIEW PROYECTO_COMPRAS_GLOBAL AS
SELECT ID_COMPRA, ID_METODO_PAGO, ID_CLIENTE, FECHA, MONTO, CANTIDAD, 'MM' AS SUCURSAL FROM PROYECTO_COMPRAS
UNION (
  SELECT ID_COMPRA, ID_METODO_PAGO, ID_CLIENTE, FECHA, MONTO, CANTIDAD, 'JP' AS SUCURSAL FROM PROYECTO_COMPRAS@JP
) UNION (
  SELECT ID_COMPRA, ID_METODO_PAGO, ID_CLIENTE, FECHA, MONTO, CANTIDAD, 'KR' AS SUCURSAL FROM PROYECTO_COMPRAS@KR
) UNION (
  SELECT ID_COMPRA, ID_METODO_PAGO, ID_CLIENTE, FECHA, MONTO, CANTIDAD, 'MC' AS SUCURSAL FROM PROYECTO_COMPRAS@MC
) ORDER BY SUCURSAL
