CREATE OR REPLACE VIEW VENTAS AS
SELECT L.ID_LIBRO AS LIBRO, S.ID_SUCURSAL AS SUCURSAL, C.ID_CLIENTE AS CLIENTE, T.ID_TIEMPO AS TIEMPO, PC.CANTIDAD AS CA, PC.MONTO AS MT
FROM D_TIEMPO T, D_LIBROS L, D_SUCURSAL S, D_CLIENTES C, PROYECTO_COMPRAS@JP PC, PROYECTO_COMPRASLIBRO@JP PCL
WHERE TO_DATE(PC.FECHA)= TO_DATE(T.FECHA) AND S.NOMBRE =  'JP' AND C.ID_CLIENTE = PC.ID_CLIENTE AND PC.ID_COMPRA = PCL.ID_COMPRA AND PCL.ID_LIBRO = L.ID_LIBRO
UNION
SELECT L.ID_LIBRO AS LIBRO, S.ID_SUCURSAL AS SUCURSAL, C.ID_CLIENTE AS CLIENTE, T.ID_TIEMPO AS TIEMPO, PC.CANTIDAD AS CA, PC.MONTO AS MT
FROM D_TIEMPO T, D_LIBROS L, D_SUCURSAL S,D_CLIENTES C, PROYECTO_COMPRAS@MM PC, PROYECTO_COMPRASLIBRO@MM PCL
WHERE TO_DATE(PC.FECHA)= TO_DATE(T.FECHA) AND S.NOMBRE =  'MM' AND C.ID_CLIENTE = PC.ID_CLIENTE AND PC.ID_COMPRA = PCL.ID_COMPRA AND PCL.ID_LIBRO = L.ID_LIBRO
UNION
SELECT L.ID_LIBRO AS LIBRO, S.ID_SUCURSAL AS SUCURSAL, C.ID_CLIENTE AS CLIENTE, T.ID_TIEMPO AS TIEMPO, PC.CANTIDAD AS CA, PC.MONTO AS MT
FROM D_TIEMPO T, D_LIBROS L, D_SUCURSAL S,D_CLIENTES C, PROYECTO_COMPRAS@MC PC, PROYECTO_COMPRASLIBRO@MC PCL
WHERE TO_DATE(PC.FECHA)= TO_DATE(T.FECHA) AND S.NOMBRE =  'MC' AND C.ID_CLIENTE = PC.ID_CLIENTE AND PC.ID_COMPRA = PCL.ID_COMPRA AND PCL.ID_LIBRO = L.ID_LIBRO
UNION
SELECT L.ID_LIBRO AS LIBRO, S.ID_SUCURSAL AS SUCURSAL, C.ID_CLIENTE AS CLIENTE, T.ID_TIEMPO AS TIEMPO, PC.CANTIDAD AS CA, PC.MONTO AS MT
FROM D_TIEMPO T, D_LIBROS L, D_SUCURSAL S,D_CLIENTES C, PROYECTO_COMPRAS@KR PC, PROYECTO_COMPRASLIBRO@KR PCL
WHERE TO_DATE(PC.FECHA)= TO_DATE(T.FECHA) AND S.NOMBRE =  'KR' AND C.ID_CLIENTE = PC.ID_CLIENTE AND PC.ID_COMPRA = PCL.ID_COMPRA AND PCL.ID_LIBRO = L.ID_LIBRO


CREATE OR REPLACE PROCEDURE ACTUALIZA_VENTAS(
  FECHAINICIAL IN DATE,
  FECHAFINAL IN DATE
)
AS
  vFechaInicial date;
  vFechaFinal date;
  V_IDVENTA number;

  CURSOR C_TIEMPO IS
  SELECT ID_VENTA FROM H_VENTAS H, D_TIEMPO T WHERE H.ID_TIEMPO = T.ID_TIEMPO AND T.FECHA BETWEEN FECHAINICIAL AND FECHAFINAL;

  CURSOR C_VENTAS IS
  SELECT V.LIBRO, V.SUCURSAL, V.CLIENTE, V.TIEMPO, COUNT(V.LIBRO) AS CANT_LIBROS, SUM(V.MT) AS MONTO
  FROM VENTAS V, D_TIEMPO DT WHERE V.TIEMPO = DT.ID_TIEMPO AND DT.FECHA BETWEEN FECHAINICIAL AND FECHAFINAL
  GROUP BY (V.LIBRO, V.SUCURSAL, V.CLIENTE, V.TIEMPO);

  V_VENTASROW C_VENTAS%ROWTYPE;

BEGIN

  OPEN C_TIEMPO;
  FETCH C_TIEMPO INTO V_IDVENTA;

  WHILE C_TIEMPO%FOUND LOOP
    DELETE FROM H_VENTAS WHERE ID_VENTA = V_IDVENTA;
    FETCH C_TIEMPO INTO V_IDVENTA;
  END LOOP;
  CLOSE C_TIEMPO;

  OPEN C_VENTAS;

  FETCH C_VENTAS INTO V_VENTASROW;
  WHILE C_VENTAS%FOUND LOOP
    INSERT INTO H_VENTAS VALUES(SEQ_H_VENTAS.NEXTVAL, V_VENTASROW.LIBRO, V_VENTASROW.SUCURSAL, V_VENTASROW.CLIENTE, V_VENTASROW.TIEMPO, V_VENTASROW.CANT_LIBROS, V_VENTASROW.MONTO);
    FETCH C_VENTAS INTO V_VENTASROW;
  END LOOP;
CLOSE C_VENTAS;
COMMIT;
END ACTUALIZA_VENTAS;
EXECUTE ACTUALIZA_STOCK;
